from typing import Iterator, Tuple


class Scene:
    def __init__(self, name: str, description: str, token: str, first_sample_token: str, last_sample_token: str) -> None: ...
    def get_name(self) -> str: ...
    def get_description(self) -> str: ...
    def get_token(self) -> str: ...
    def get_first_sample_token(self) -> str: ...
    def get_last_sample_token(self) -> str: ...
    def __repr__(self) -> str: ...


class SceneManager:
    def __init__(self) -> None: ...
    def read_scenes(self, filename: str) -> None: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, token: str) -> Scene: ...
    def __iter__(self) -> Iterator[Tuple[str, Scene]]: ...