from typing import Iterator, Tuple, Optional, List

class Token:
    value: str
    def __init__(self, token_str: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...


class Scene:
    def __init__(self, name: str, description: str, token: str, first_sample_token: str, last_sample_token: str) -> None: ...
    def __init__(self, name: str, description: str, token: Token, first_sample_token: Token, last_sample_token: Token) -> None: ...
    def get_name(self) -> str: ...
    def get_description(self) -> str: ...
    def get_token(self) -> Token: ...
    def get_first_sample_token(self) -> Token: ...
    def get_last_sample_token(self) -> Token: ...


class SceneManager:
    def __init__(self) -> None: ...
    def read_scenes(self, filename: str) -> None: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, token: str) -> Scene: ...
    def __iter__(self) -> Iterator[Tuple[Token, Scene]]: ...


class Sample:
    def __init__(self, token: Token, scene_token: Token, timestamp: int) -> None: ...
    def get_token(self) -> Token: ...
    def get_scene_token(self) -> Token: ...
    def get_timestamp(self) -> int: ...
    def get_prev_sample(self) -> Optional[Sample]: ...
    def get_next_sample(self) -> Optional[Sample]: ...
    def set_prev_sample(self, prev: Optional[Sample]) -> None: ...
    def set_next_sample(self, next: Optional[Sample]) -> None: ...


class SampleSequence:
    def __init__(self) -> None: ...
    def read_samples(self, filename: str, scene_token: Token) -> None: ...
    def add_sample(self, token: Token, scene_token: Token, timestamp: int, prev_token: Token = Token(""), next_token: Token = Token("")) -> None: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Sample: ...
    def get_tokens(self) -> List[Token]: ...
    def __iter__(self) -> Iterator[Sample]: ...


class DataItem:
    def __init__(self, timestamp: int, filename: str) -> None: ...
    def get_timestamp(self) -> int: ...
    def get_filename(self) -> str: ...
    def get_prev_sample(self) -> Optional[DataItem]: ...
    def get_next_sample(self) -> Optional[DataItem]: ...


class SensorBase:
    def __init__(self, token: Token, channel: str, modality: str) -> None: ...
    def get_token(self) -> Token: ...
    def get_channel(self) -> str: ...
    def get_modality(self) -> str: ...
    def size(self) -> int: ...
    def add_file(self, filename: str, timestamp: int) -> None: ...
    def __getitem__(self, index: int) -> DataItem: ...
    def __len__(self) -> int: ...


class SensorManager:
    def __init__(self) -> None: ...
    def read_sensors(self, filename: str, filter_tokens: List[Token] = []) -> None: ...
    def add_sensor(self, token: Token, channel: str, modality: str) -> None: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, token: str) -> SensorBase: ...
    def __iter__(self) -> Iterator[SensorBase]: ...


# class MANTruckDataset:
#     def __init__(
#         self,
#         datasets_folder: str,
#         dataset_name: str,
#         scene_token: str,
#         sensor_tokens: Optional[List[str]] = []
#     ) -> None:
#         """Initialize MANTruckDataset.
        
#         Args:
#             datasets_folder: Path to datasets root folder
#             dataset_name: Name of the dataset
#             scene_token: Token of the scene to load
#             sensor_tokens: Optional list of sensor tokens to filter
#         """
#         ...
    
#     def get_sensor_manager(self) -> SensorManager:
#         """Get the sensor manager containing all loaded sensors.
        
#         Returns:
#             SensorManager instance with all loaded sensors
#         """
#         ...