from enum import Enum
from typing import Iterator, Tuple, Optional, List, overload

class Token:
    value: str
    def __init__(self, token_str: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...


class Scene:
    def __init__(self, name: str, description: str, token: str, first_sample_token: str, last_sample_token: str) -> None: ...
    def __init__(self, name: str, description: str, token: Token, first_sample_token: Token, last_sample_token: Token) -> None: ...
    def get_name(self) -> str: ...
    def get_description(self) -> str: ...
    def get_token(self) -> Token: ...
    def get_first_sample_token(self) -> Token: ...
    def get_last_sample_token(self) -> Token: ...


class SceneManager:
    def __init__(self) -> None: ...
    def read_scenes(self, filename: str) -> None: ...
    @overload
    def add_scene(self, name: str, description: str, token: str, first_sample_token: str, last_sample_token: str) -> None: ...
    @overload
    def add_scene(self, name: str, description: str, token: Token, first_sample_token: Token, last_sample_token: Token) -> None: ...
    def get_scenes(self) -> List[Scene]: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, token: str) -> Scene: ...
    @overload
    def __getitem__(self, token: Token) -> Scene: ...
    def __iter__(self) -> Iterator[Scene]: ...


class Sample:
    def __init__(self, token: Token, scene_token: Token, timestamp: int) -> None: ...
    def get_token(self) -> Token: ...
    def get_scene_token(self) -> Token: ...
    def get_timestamp(self) -> int: ...
    def get_prev_sample(self) -> Optional[Sample]: ...
    def get_next_sample(self) -> Optional[Sample]: ...
    def set_prev_sample(self, prev: Optional[Sample]) -> None: ...
    def set_next_sample(self, next: Optional[Sample]) -> None: ...


class SampleManager:
    def __init__(self) -> None: ...
    def read_samples(self, filename: str) -> int: ...
    def add_sample(self, token: Token, scene_token: Token, timestamp: int, prev_token: Token = Token(""), next_token: Token = Token("")) -> None: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Sample: ...
    def get_samples(self) -> List[Sample]: ...
    def get_samples_by_scene(self, scene_token: Token) -> List[Sample]: ...
    def __iter__(self) -> Iterator[Sample]: ...


class DataItem:
    def __init__(self, timestamp: int, filename: str) -> None: ...
    def get_timestamp(self) -> int: ...
    def get_filename(self) -> str: ...
    def get_prev_sample(self) -> Optional[DataItem]: ...
    def get_next_sample(self) -> Optional[DataItem]: ...


class Modality(Enum):
    CAMERA = 0
    LIDAR = 1
    RADAR = 2
    IMU = 3
    def __str__(self) -> str: ...

class SensorBase:
    @overload
    def __init__(self, token: str, channel: str, modality: str) -> None: ...
    @overload
    def __init__(self, token: Token, channel: str, modality: str) -> None: ...
    @overload
    def __init__(self, token: Token, channel: str, modality: Modality) -> None: ...
    def get_token(self) -> Token: ...
    def get_channel(self) -> str: ...
    def get_modality(self) -> str: ...


class SensorManager:
    def __init__(self) -> None: ...
    def read_sensors(self, filename: str) -> bool: ...
    def get_sensors(self) -> List[SensorBase]: ...
    def size(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> SensorBase: ...
    @overload
    def __getitem__(self, token: Token) -> SensorBase: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[SensorBase]: ...


class MANTruckDataset:
    def __init__(self, dataset_folder: str, metadata_folder: str) -> None: ...
    def get_scene_manager(self) -> SceneManager: ...
    def get_sensor_manager(self) -> SensorManager: ...
    # def get_calibration_manager(self) -> CalibrationManager: ...
    def get_sample_manager(self) -> SampleManager: ...
    # def get_data_manager(self) -> DataManager: ...
    # def get_data(self, scene: Scene, sensor: SensorBase) -> List[DataSample]: ...
